name: Android
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
        - debug-armeabi-v7a
        - debug-arm64-v8a
        - release-armeabi-v7a
        - release-arm64-v8a
        package:
        - jiten
        - jiten_nodb
    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      JAVA_HOME_11_X64: /usr/lib/jvm/java-11-openjdk-amd64
      JAVA_HOME_8_X64: ''
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo make -C android _setup_root
        sudo apt-get purge -y adoptopenjdk-11-hotspot adoptopenjdk-8-hotspot
        make -C android _setup_user
    - name: System info
      run: |
        lsb_release -a
        git --version && python --version
        java -version && javac -version
        # env | grep -Eiv 'token|secret|github'
    - name: Build
      run: make -C android ${{ matrix.target }}
      env:
        APP_PACKAGE_NAME: ${{ matrix.package }}
    - name: SHASUMS
      run: |
        sha1sum   android/bin/*.apk
        sha256sum android/bin/*.apk
        sha512sum android/bin/*.apk
    - name: Version
      run: touch VERSION_"$(git describe --always)"
    - uses: actions/upload-artifact@v2
      with:
        name: jiten-APK
        path: |
          VERSION_*
          android/bin/*.apk
          !android/bin/*nodb*.apk
    - uses: actions/upload-artifact@v2
      with:
        name: jiten-nodb-APK
        path: |
          VERSION_*
          android/bin/*nodb*.apk
