name: Android
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo make -C android _setup_root
        make -C android _setup_user
    - name: Cache ~/.buildozer
      uses: actions/cache@v2
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}
    - name: Build
      run: make -C android
    - uses: actions/upload-artifact@v2
      with:
        name: APK
        path: android/bin/*.apk
